version: '3'

services:
  app:
    build: 
      context: .
    volumes:
      - .:/workspace:cached
    links:
      - mongo_db
    depends_on:
      - mongo_db
    environment:
      APP_NAME: learn dev containers
      PORT: 3002
      DB_USER: mongo
      DB_PASSWORD: password
      DB_NAME_IP: mongo_db
      DB_PORT: 27017
      DB_NAME: node-crud-app
    ports:
      - "3002:3002"

  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
      - ./mongo-init/createAdmin.js:/docker-entrypoint-initdb.d/createAdmin.js:ro
    ports:
      - "27017:27017"
  
volumes:
  mongo_db: {}
