version: '3'

services:
  app:
    build: 
      context: .
    volumes:
      - .:/workspace:cached
    links:
      - mongo_db
    depends_on:
      - mongo_db
    environment:
      APP_NAME: learn dev containers
      PORT: 3005
      DB_USER: mongoadmin
      DB_PASSWORD: mongopasswd
      DB_NAME_IP: mongo_db
      DB_PORT: 27017
      DB_NAME: node-crud-app
    ports:
      - "3005:3005"

  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopasswd
      - MONGO_INITDB_DATABASE=node-crud-app
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
  
volumes:
  mongo_db: {}
