version: '3'

services:
  app:
    build: 
      context: .
    command: tail -f /dev/null
    volumes:
      - .:/workspace:cached
    links:
      - mongo_db
    depends_on:
      - mongo_db
    environment:
      APP_NAME: learn dev containers
      PORT: 3000
      DB_USER: mongo
      DB_PASSWORD: password
      DB_NAME_IP: mongo_db
      DB_PORT: 27017
      DB_NAME: node-crud-app
    ports:
      - "3000:3000"

  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
  
volumes:
  mongo_db: {}
